

adjectives = {
    'other': ('other', 'outro(a)'),
    'new': ('new', 'novo(a)'),
    'good': ('good', 'bom(a)'),
    'high': ('high', 'alto(a)'),
    'old': ('old', 'velho(a)'),
    'great': ('great', 'ótimo(a)'),
    'big': ('big', 'grande'),
    'american': ('american', 'americano(a)'),
    'small': ('small', 'pequeno(a)'),
    'large': ('large', 'grande'),
    'national': ('national', 'nacional'),
    'young': ('young', 'novo(a)'),
    'different': ('different', 'diferente'),
    'black': ('black', 'preto(a)'),
    'long': ('long', 'longo'),
    'little': ('little', 'pequeno'),
    'important': ('important', 'importante'),
    'political': ('political', 'político'),
    'bad': ('bad', 'ruim/mau/má'),
    'white': ('white', 'branco(a)'),
    'real': ('real', 'real'),
    'best': ('best', 'melhor'),
    'right': ('right', 'certo/correto'),
    'social': ('social', 'social'),
    'only': ('only', 'apenas'),
    'public': ('public', 'público'),
    'sure': ('sure', 'certo/seguro'),
    'low': ('low', 'baixo(a)'),
    'early': ('early', 'cedo'),
    'able': ('able', 'capaz'),
    'human': ('human', 'humano(a)'),
    'local': ('local', 'local'),
    'late': ('late', 'atrasado(a)'),
    'hard': ('hard', 'difícil'),
    'major': ('major', 'principal'),
    'better': ('better', 'melhor'),
    'economic': ('economic', 'econômico'),
    'strong': ('strong', 'forte'),
    'possible': ('possible', 'possível'),
    'whole': ('whole', 'inteiro/completo'),
    'free': ('free', 'gratuito(a)/livre'),
    'military': ('military', 'militar'),
    'true': ('true', 'verdadeiro(a)'),
    'federal': ('federal', 'federal'),
    'international': ('international', 'internacional'),
    'full': ('full', 'completo'),
    'special': ('special', 'especial'),
    'easy': ('easy', 'fácil'),
    'clear': ('clear', 'claro/evidente'),
    'recent': ('recent', 'recente'),
    'certain': ('certain', 'certo(a)'),
    'personal': ('personal', 'pessoal'),
    'open': ('open', 'aberto(a)'),
    'red': ('red', 'vermelho(a)'),
    'difficult': ('difficult', 'difícil'),
    'available': ('available', 'disponível'),
    'likely': ('likely', 'provável'),
    'short': ('short', 'curto(a)'),
    'single': ('single', 'único(a)'),
    'medical': ('medical', 'médico(a)'),
    'current': ('current', 'atual'),
    'wrong': ('wrong', 'errado(a)'),
    'private': ('private', 'privado(a)'),
    'past': ('past', 'passado'),
    'foreign': ('foreign', 'estrangeiro(a)'),
    'fine': ('fine', 'bom(a)/excelente'),
    'common': ('common', 'comum'),
    'poor': ('poor', 'pobre'),
    'natural': ('natural', 'natural'),
    'significant': ('significant', 'significativo'),
    'similar': ('similar', 'semelhante/similar/parecido'),
    'hot': ('hot', 'quente'),
    'dead': ('dead', 'morto(a)'),
    'central': ('central', 'central'),
    'happy': ('happy', 'feliz'),
    'serious': ('serious', 'sério(a)'),
    'ready': ('ready', 'pronto(a)'),
    'simple': ('simple', 'simples'),
    'left': ('left', 'esquerdo(a)'),
    'physical': ('physical', 'físico(a)'),
    'general': ('general', 'geral'),
    'environmental': ('environmental', 'ambiental'),
    'financial': ('financial', 'financeiro(a)'),
    'blue': ('blue', 'azul'),
    'democratic': ('democratic', 'democrático(a)'),
    'dark': ('dark', 'escuro(a)'),
    'various': ('various', 'vários(as)'),
    'entire': ('entire', 'inteiro(a)'),
    'close': ('close', 'fechado(a)'),
    'legal': ('legal', 'legal'),
    'religious': ('religious', 'religioso(a)'),
    'cold': ('cold', 'frio(a)'),
    'final': ('final', 'final'),
    'main': ('main', 'principal'),
    'green': ('green', 'verde'),
    'nice': ('nice', 'legal'),
    'huge': ('huge', 'enorme'),
    'popular': ('popular', 'popular'),
    'traditional': ('traditional', 'tradicional'),
    'cultural': ('cultural', 'cultural'),
    'stupid': ('stupid', 'estúpido'),
    'irrelevant': ('irrelevant', 'irrelevante'),
    'sweet': ('sweet', 'doce'),
    'angry': ('angry', 'com raiva/irritado(a)/zangado(a)'),
    'ambitious': ('ambitious', 'ambicioso(a)'),
    'indifferent': ('indifferent', 'indiferente'),
    'marvelous': ('marvelous', 'maravilhoso(a)'),
    'identical': ('identical', 'idêntico(a)'),
    'clever': ('clever', 'esperto(a)/inteligente'),
    'enthusiastic': ('enthusiastic', 'entusiasmado(a)'),
    'vibrant': ('vibrant', 'vibrante'),
    'affirmative': ('affirmative', 'afirmativo(a)'),
    'negative': ('negative', 'negativo'),
    'comprehensive': ('comprehensive', 'abrangente'),
    'intuitive': ('intuitive', 'intuitivo(a)'),
    'strange': ('strange', 'estranho(a)'),
    'weird': ('weird', 'estranho(a)'),
    'odd': ('odd', 'estranho(a)'),
    'worthy': ('worthy', 'digno(a)'),
    'flexible': ('flexible', 'flexível'),
    'obnoxiously': ('obnoxiously', 'detestável'),
    'fast': ('fast', 'ligeiro(a)/rápido(a)'),
    'golden': ('golden', 'dourado(a)')
}

adjectives_keys = [word for word in adjectives]

adjectives_keys_index0 = [word[0] for word in adjectives.values()]
adjectives_keys_index1 = [word[1] for word in adjectives.values()]

if __name__ == '__main__':
    bricks = '=' * 100

    print(bricks)
    print(f"{len(adjectives) = }")
    print(f"{len(adjectives_keys) = }")
    print(f"{len(adjectives_keys_index0) = }")
    print(f"{len(adjectives_keys_index1) = }")

    print(bricks)
    print(f"{adjectives = }")
    print(f"{adjectives_keys = }")
    print(f"{adjectives_keys_index0 = }")
    print(f"{adjectives_keys_index1 = }")
