

fut_dict_uniques = {
    'to be': ('will be', 'serei/estarei', 'serão/estarão'),
    'to have': ('will have', 'possuirei/terei', 'possuirão/terão'),
    'to do': ('will do' 'farei', 'farão'),
}

fut = {
    'to say': ('will say', 'direi/falarei'),
    'to go': ('will go', 'irei'),
    'to get': ('will get', 'adquirirei/conseguirei/obterei/pegarei'),
    'to make': ('will make', 'criarei/farei'),
    'to know': ('will know', 'conhecerei/saberei'),
    'to think': ('will think', 'acharei/pensarei'),
    'to take': ('will take', 'levarei/pegarei/tomarei'),
    'to see': ('will see', 'verei'),
    'to come': ('will come', 'chegarei/virei'),
    'to want': ('will want', 'pretenderei/quererei'),
    'to look': ('will look', 'olharei/verei'),
    'to use': ('will use', 'usarei'),
    'to find': ('will find', 'acharei/encontrarei'),
    'to give': ('will give', 'darei'),
    'to tell': ('will tell', 'contarei/direi'),
    'to work': ('will work', 'funcionarei/trabalharei'),
    'to call': ('will call', 'chamarei/telefonarei'),
    'to try': ('will try', 'experimentarei/tentarei'),
    'to ask': ('will ask', 'pedirei/perguntarei'),
    'to need': ('will need', 'necessitarei/precisarei'),
    'to feel': ('will feel', 'sentirei'),
    'to become': ('will become', 'tornarei'),
    'to leave': ('will leave', 'abandonarei/deixarei/sairei'),
    'to put': ('will put', 'colocarei/porei'),
    'to mean': ('will mean', 'significarei'),
    'to keep': ('will keep', 'continuarei/guardarei/manterei'),
    'to let': ('will let', 'deixarei/permitirei'),
    'to begin': ('will begin', 'começarei/iniciarei'),
    'to seem': ('will seem', 'parecerei'),
    'to help': ('will help', 'ajudarei/auxiliarei'),
    'to talk': ('will talk', 'conversarei/falarei'),
    'to turn': ('will turn', 'transformarei/virarei'),
    'to start': ('will start', 'começarei/iniciarei'),
    'to show': ('will show', 'apresentarei/mostrarei'),
    'to hear': ('will hear', 'escutarei/ouvirei'),
    'to play': ('will play', 'jogarei/tocarei'),
    'to run': ('will run', 'correrei'),
    'to move': ('will move', 'moverei/mexerei'),
    'to like': ('will like', 'gostarei'),
    'to live': ('will live', 'morarei/viverei'),
    'to believe': ('will believe', 'acreditarei/crerei'),
    'to hold': ('will hold', 'manterei/segurarei'),
    'to bring': ('will bring', 'trarei'),
    'to happen': ('will happen', 'acontecerei/ocorrerei'),
    'to write': ('will write', 'escreverei'),
    'to provide': ('will provide', 'fornecerei/proporcionarei'),
    'to sit': ('will sit', 'sentarei'),
    'to stand': ('will stand', 'levantarei/permanecerei'),
    'to lose': ('will lose', 'perderei'),
    'to pay': ('will pay', 'pagarei'),
    'to meet': ('will meet', 'conhecerei/encontrarei'),
    'to include': ('will include', 'incluirei'),
    'to continue': ('will continue', 'continuarei'),
    'to set': ('will set', 'configurarei/definirei/estabelecerei/porei'),
    'to learn': ('will learn', 'aprenderei'),
    'to change': ('will change', 'alterarei/mudarei'),
    'to lead': ('will lead', 'conduzirei/liderarei'),
    'to understand': ('will understand', 'compreenderei/entenderei'),
    'to watch': ('will watch', 'olharei/observarei/verei'),
    'to follow': ('will follow', 'acompanharei/seguirei'),
    'to stop': ('will stop', 'impedirei/pararei'),
    'to create': ('will create', 'criarei'),
    'to speak': ('will speak', 'conversarei/falarei'),
    'to read': ('will read', 'lerei'),
    'to allow': ('will allow', 'autorizarei/permitirei'),
    'to add': ('will add', 'acrescentarei/adicionarei'),
    'to spend': ('will spend', 'gastarei/passarei'),
    'to grow': ('will grow', 'aumentarei/crescerei'),
    'to open': ('will open', 'abrirei'),
    'to walk': ('will walk', 'andarei/caminharei'),
    'to win': ('will win', 'ganharei/vencerei'),
    'to offer': ('will offer', 'oferecerei/proporei'),
    'to remember': ('will remember', 'lembrarei/recordarei'),
    'to love': ('will love', 'adorarei/amarei'),
    'to consider': ('will consider', 'considerarei'),
    'to appear': ('will appear', 'aparecerei'),
    'to buy': ('will buy', 'comprarei'),
    'to wait': ('will wait', 'esperarei'),
    'to serve': ('will serve', 'servirei'),
    'to die': ('will die', 'falecerei/morrerei'),
    'to send': ('will send', 'enviarei/mandarei'),
    'to expect': ('will expect', 'esperarei'),
    'to build': ('will build', 'construirei'),
    'to stay': ('will stay', 'ficarei/permanecerei'),
    'to fall': ('will fall', 'cairei'),
    'to cut': ('will cut', 'cortarei'),
    'to reache': ('will reache', 'alcançarei/atingirei/chegarei a'),
    'to kill': ('will kill', 'matarei'),
    'to remain': ('will remain', 'ficarei/permanecerei'),
    'to suggest': ('will suggest', 'irei sugerir'),
    'to raise': ('will raise', 'aumentarei/criarei alguém,algo/levantarei'),
    'to pass': ('will pass', 'passarei'),
    'to sell': ('will sell', 'venderei'),
    'to require': ('will require', 'exigirei/necessitarei'),
    'to report': ('will report', 'relatarei/reportarei'),
    'to decide': ('will decide', 'decidirei'),
    'to pull': ('will pull', 'puxarei'),
    'to break': ('will break', 'romperei/quebrarei'),
    'to acquire': ('will acquire', 'adquirirei/comprarei/obterei'),
    'to realize': ('will realize', 'perceberei/realizarei'),
    'to manage': ('will manage', 'administrarei/irei gerir'),
    'to develop': ('will develop', 'crescerei/desenvolverei'),
    'to trust': ('will trust', 'confiarei'),
    'to imagine': ('will imagine', 'imaginarei'),
    'to step': ('will step', 'pisarei'),
    'to regret': ('will regret', 'arrependerei/lamentarei'),
    'to manipulate': ('will manipulate', 'manipularei'),
    'to dream': ('will dream', 'sonharei'),
    'to discuss': ('will discuss', 'debaterei/discutirei'),
    'to drink': ('will drink', 'beberei'),
    'to eat': ('will eat', 'comerei'),
    'to skip': ('will skip', 'pularei/saltarei'),
    'to repeat': ('will repeat', 'repetirei'),
    'to guess': ('will guess', 'adivinharei/irei supor'),
    'to select': ('will select', 'selecionarei'),
    'to click': ('will click', 'clicarei'),
}                                           # 'to say': ('will say', 'direi/falarei')
fut_keys = [word for word in fut]                     # 'to say'
fut_keys_index0 = [word[0] for word in fut.values()]  # 'will say'
fut_keys_index1 = [word[1] for word in fut.values()]  # 'direi/falarei'


if __name__ == '__main__':
    bricks = '=' * 100

    print(bricks)
    print(f"{len(fut) = }")
    print(f"{len(fut_keys) = }")
    print(f"{len(fut_keys_index0) = }")
    print(f"{len(fut_keys_index1) = }")

    print(bricks)
    print(f"{fut = }")
    print(f"{fut_keys = }")
    print(f"{fut_keys_index0 = }")
    print(f"{fut_keys_index1 = }")
